name: Import open source standard labels

on:
  push:
    branches: [main]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: EddieHubCommunity/gh-action-open-source-labels@v0.2.2
        with:
          github-token: ${{ secrets.MILAN_SECRET_TOKEN }}
          owner-name: "IAmTamal"
          repository-name: "IAmTamal/Milan"
